#!/usr/bin/env python3
"""Validate that one CD-LAM wheel is complete and free of generated bytecode."""

from __future__ import annotations

import argparse
from pathlib import Path, PurePosixPath
from zipfile import BadZipFile, ZipFile


REQUIRED_PACKAGE_FILES = {
    "cd_lam/__init__.py",
    "cd_lam/__main__.py",
    "cd_lam/data/action.py",
    "cd_lam/data/manifests.py",
    "cd_lam/training/runner.py",
}


def check_wheel(path: Path) -> tuple[int, str]:
    if not path.is_file() or path.suffix != ".whl":
        raise ValueError(f"wheel does not exist or has the wrong suffix: {path}")
    try:
        with ZipFile(path) as archive:
            names = archive.namelist()
            bad_member = archive.testzip()
    except BadZipFile as exc:
        raise ValueError(f"invalid wheel archive: {path}: {exc}") from exc
    if bad_member is not None:
        raise ValueError(f"wheel member failed CRC validation: {bad_member}")

    name_set = set(names)
    missing = sorted(REQUIRED_PACKAGE_FILES - name_set)
    if missing:
        raise ValueError(f"wheel is missing required package files: {missing}")

    generated = sorted(
        name
        for name in names
        if "/__pycache__/" in name or name.endswith((".pyc", ".pyo"))
    )
    if generated:
        raise ValueError(f"wheel contains generated bytecode: {generated}")

    unsafe = []
    for name in names:
        member = PurePosixPath(name)
        if member.is_absolute() or ".." in member.parts:
            unsafe.append(name)
    if unsafe:
        raise ValueError(f"wheel contains unsafe member paths: {sorted(unsafe)}")

    metadata = sorted(name for name in names if name.endswith(".dist-info/METADATA"))
    entry_points = sorted(
        name for name in names if name.endswith(".dist-info/entry_points.txt")
    )
    if len(metadata) != 1 or len(entry_points) != 1:
        raise ValueError(
            "wheel must contain exactly one METADATA and one entry_points.txt file"
        )
    return len(names), metadata[0]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("wheel", type=Path)
    args = parser.parse_args()
    count, metadata = check_wheel(args.wheel)
    print(
        f"wheel_check path={args.wheel} files={count} generated_files=0 "
        f"metadata={metadata}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
